name: CICD

on:
  workflow_dispatch:
    inputs:
      environment:
        description: This is the environment value where this workflow runs
        default: dev
        required: true
        type: choice
        options:
          - dev
          - prod
          - staging

jobs:

  code:
    runs-on: self-hosted
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Code stage
        run: echo "Code cloned from GitHub"

  build:
    needs: [code]
    runs-on: self-hosted
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Build Docker Container
        run: echo "Docker container build"

  test:
    needs: [build]
    runs-on: self-hosted
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Test the container
        run: echo "Testing the container"

  deploy:
    if: inputs.environment == 'dev'
    needs: [build, test]
    runs-on: self-hosted
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Deploying the app
        run: echo "Docker compose deployed the app"